### PR TITLE
Various Fixes

### PR DESCRIPTION
**Pull request by ghost**
There has been two fixes implemented within this pull request and some minor tiding of the code.

**1. Fixed Sitemap URL's**

Currently the sitemap URL is using the following format: 
http://www.domain.com/app.php/sitemap/sitemap.xml

I have changed this to:
http://www.domain.com/app.php/sitemap.xml

When enabling the "URL Rewriting" option located on the "ACP > SERVER CONFIGURATION > Server settings" page, the URL used and displayed now correctly changes to the following format:
http://www.domain.com/sitemap.xml

**2. Event language Fix**

Fixed the issue where the common.php language file isn't being called when a forum has no data: 
https://www.phpbb.com/community/viewtopic.php?f=456&t=2390131&start=60#p14765781

**3. Tidy Code**
Cleaned some code to bring it in line with phpBB 3.2 

There are no other issues with this extension at this present time.

### CODE REVIEW

**Comment by Galixte** [comment]
Hi @CrazyC0d3r, maybe you could create a fork to publish your updates, and maybe later ask to reopen the original topic here: https://www.phpbb.com/community/viewtopic.php?f=456&t=2390131. ;)

**Comment by ghost** [comment]
Hi @Galixte, will wait a few weeks. I want to see if @LotusJeff responds or continues with the development of this extension before moving on with it. If Jeff has abandoned this extension, I will be continuing with it's development myself as I use it on my forum.

**Comment by LotusJeff** [comment]
This isn't abandoned.  I live in Houston, TX and am a little busy right now dealing with some issues. I will look at the changes next week.

As a quick note, the change to app.php/sitemap.xml will not pass phpbb coding/naming standards. That is why it is app.php/sitemap/sitemap.xml

**Comment by Galixte** [comment]
https://github.com/phpbb-extensions/pages permits to have this kind of path: ```./pagename/``` instead of ```./page/pagename/``` maybe you can take a look on it. ;)

**Comment by LotusJeff** [comment]
phpBB does not have to follow their own coding standards. I originally started with a app.php/sitemap.xml and was told it had to be app.php/sitemap/sitemap.xml.

Also remember, that many people use phpBB as a subsection of their website.  For them, the link is /forum_name/app.php/sitemap/sitemap.xml.  With today's webmaster tools, meta tags and robot.txt files, the sitemap can live anywhere.

**Comment by ghost** [comment]
@LotusJeff, great to hear that this extension isn't being abandoned!

@Galixte, @LotusJeff is correct, phpBB don't always follow the same rules or coding standards they set for everyone else.

@LotusJeff, if you continue down the route of using http://www.domain.com/app.php/sitemap/sitemap.xml (which I guess you will have to in order to pass validation by the phpBB team), you still need to implement the URL fixes because currently, URL's are hard coded using `generate_board_url()."/app.php/sitemap/sitemap.xml";`.

EDIT: I have just updated my pull request and reversed my changes to the routing.yml file so that the extensions URL continues to use http://www.domain.com/app.php/sitemap/sitemap.xml.

**Comment by ghost** [comment]
I can't get the travis to pass this pull request!?!

Test results for extension:
```
Warning: Can't detect the file type for phpunit.xml.dist, handling it as a binary file.
Warning: Can't detect the file type for style.xsl, handling it as a binary file.
Fatal error: Can not find '$vars = array();'-line for event 'lotusjeff.sitemap_additional_data' in file '/controller/sitemap.php:657'. Are you using UNIX style linefeeds?
Error: Packaging structure doesn't meet the extension DB policies.
Error: Using unserialize on line 151 in /acp/sitemap_module.php
Error: Using unserialize on line 103 in /controller/sitemap.php
Error: Using unserialize on line 170 in /controller/sitemap.php
Error: Using unserialize on line 350 in /controller/sitemap.php
Error: Using unserialize on line 454 in /controller/sitemap.php
```

This is original code! How did you get it to pass? By using php 5.3?

**Comment by Galixte** [comment]
Hi @CrazyC0d3r, maybe it’s time to fork this project. ;)

**Comment by ghost** [comment]
> Hi @CrazyC0d3r, maybe it’s time to fork this project. ;)

Yea, looks like it's been abandoned after all. I still maintain a copy of this extension and use it on my live site.

**Comment by Galixte** [comment]
@CrazyC0d3r Could you share this please on a fork?

**Comment by ghost** [comment]
Sure, I have overhauled the entire extension. I will get it forked today/tomorrow.

**Comment by Galixte** [comment]
Thanks: https://github.com/CrazyC0d3r/sitemap!

**Pull request closed without merging**
